/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:542ac158-d36b-4e5a-939c-ea6646da4d29",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_8najILbXu",
    "aws_user_pools_web_client_id": "36s6qj35u16mic6gcudk4vm7pv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://j7ufzao7pjdavhimn4sqs3vqbu.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "song-storage112043-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
